from pathlib import Path

ROOT_DIR = Path(__file__).parent 
FILES_DIR = ROOT_DIR / 'files'
ICON = FILES_DIR / 'calculadora.png'

BIG_FONT_SIZE = 40
MEDIUM_FONT_SIZE = 24
SMALL_FONT_SIZE = 18
TEXT_MARGIN = 15
MINIMUN_WITH = 500

DARKER_PRIMARY_COLOR = "#057DCE"
DARKEST_PRIMARY_COLOR = "#062647"
PRIMARY_COLOR = "#1A72BB"